[package]
name = "multimap"
version = "0.2.0"
description = "A multimap implementation."
readme = "README.md"
repository = "https://github.com/havarnov/multimap"
license = "MIT"
authors = ["Håvar Nøvik <havar.novik@gmail.com>"]
documentation = "http://havarnov.github.io/multimap/multimap/index.html"
